# App Info
page_title                                : Recapt
app_icon                                  : assets/logo.png                   
company_logo                              : assets/recapt.png
app_name                                  : Recapt                                  
app_description                           : Capture Your Expenses


# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#2A2A2A"

link_color                                : "#00D4DB"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#E91E63"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#000000"
feature_icons_background_color            : "#E91E63"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME
  - vendor/bundle 

collections:
  pages:
    output: true
    permalink: /:path/
  pagesForDeliverables:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown